/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminModule;

import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;


/**
 *
 * @author compu malek
 */
public class login2 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    
    public login2() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title0 = new javax.swing.JLabel();
        select_role = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        t_username = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        login_pic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        t_role = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        title0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title0.setForeground(new java.awt.Color(0, 102, 204));
        title0.setText("LOGIN");

        select_role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        select_role.setForeground(new java.awt.Color(0, 102, 204));
        select_role.setText("Select role");

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 102, 204));
        password.setText("Password");

        t_password.setForeground(new java.awt.Color(0, 102, 204));
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });

        t_username.setForeground(new java.awt.Color(0, 102, 204));
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        t_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_usernameKeyReleased(evt);
            }
        });

        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(0, 102, 204));
        login.setText("Login");
        login.setToolTipText("");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        jLabel7.setBackground(new java.awt.Color(0, 102, 204));
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));

        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(0, 102, 204));
        username.setText("Username");

        pic.setForeground(new java.awt.Color(0, 102, 204));

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(0, 102, 204));
        register.setText("Register new account?");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        t_role.setForeground(new java.awt.Color(0, 102, 204));
        t_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_roleActionPerformed(evt);
            }
        });
        t_role.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_roleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(login)
                                        .addComponent(password))
                                    .addComponent(select_role, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_role, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(title0)))
                .addGap(80, 80, 80)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(login_pic)
                .addGap(118, 118, 118)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title0)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_role)
                    .addComponent(t_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String role1= t_role.getText();
        String username1= t_username.getText();
        String password1=t_password.getText();
        try{
            File file =new File("D:\\Files Project\\Register.txt");
            Scanner scan =new Scanner(file);
            scan.useDelimiter("[/\n]");
            while(scan.hasNext()){
                String role=scan.next();
                String username =scan.next();
                String password=scan.next();
                
            if(username1.equals(username.trim())&&password1.equals(password.trim())&&role1.equals(role.trim())){
                JOptionPane.showMessageDialog(this, "Admin Login in Sucessfully..");
                this.setVisible(false);
                new AdminMainForm().setVisible(true);
                break;
                
            }
            else if(role1.equals("client")){
                JOptionPane.showMessageDialog(this, "Client Log in Sucessfully..");
                this.setVisible(false);
                new ClientModule.ClientDashboard().setVisible(true);
                break;
                
            }
            else if(role1.equals("supplier")){
                JOptionPane.showMessageDialog(this, "Supplier Log in Sucessfully..");
                this.setVisible(false);
                new ManageSupplier().setVisible(true);
                break;
            }

            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "invalid data!");
                //break;
        }
    }//GEN-LAST:event_loginActionPerformed

    private void t_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_usernameKeyReleased
        // TODO add your handling code here:
        int position = t_username.getCaretPosition();
        t_username.setText(t_username.getText().toLowerCase());
        t_username.setCaretPosition(position);
    }//GEN-LAST:event_t_usernameKeyReleased
  register f= null;
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        if(f==null){
        f= new register();
        }
       f.setVisible(true);
       
       this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    private void t_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_roleActionPerformed

    private void t_roleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_roleKeyReleased
        // TODO add your handling code here:
        int position = t_role.getCaretPosition();
        t_role.setText(t_role.getText().toLowerCase());
        t_role.setCaretPosition(position);
    }//GEN-LAST:event_t_roleKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
                
        
        new login2().setVisible(true);
        //try{
          //  for(int i=0;i<=100;i++){
                
          //  }
            
       // }catch
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel login_pic;
    private javax.swing.JLabel password;
    private javax.swing.JLabel pic;
    private javax.swing.JButton register;
    private javax.swing.JLabel select_role;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_role;
    private javax.swing.JTextField t_username;
    private javax.swing.JLabel title0;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
