/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientModule;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import AdminModule.TotalProfit;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.text.MessageFormat;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Mostafa
 */
public class OrderDashboard extends javax.swing.JFrame {


    public OrderDashboard() {
        initComponents();
        dt();//for date
        times();//for time
        
        //Import list of products automatic
        String filepath="D:\\Files Project\\ExportProducts.txt";
        File file=new File(filepath);
        try {
        FileReader fr=new FileReader(file);
        BufferedReader br=new BufferedReader(fr);
        DefaultTableModel tab=(DefaultTableModel)ProductList.getModel();
        Object[] lines=br.lines().toArray();
        for(int i=0;i<lines.length;i++){
           String[] row=lines[i].toString().split(" ");
            tab.addRow(row);
         }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrderDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        //This is for customer inforamtion to import them automatic
        String filepath2="D:\\Files Project\\CustomerInforamtion.txt";
        File file2=new File(filepath2);
        try {
            FileReader fr=new FileReader(file2);
            BufferedReader br=new BufferedReader(fr);
            DefaultTableModel tab=(DefaultTableModel)CustomerInfo.getModel();
            Object[] lines=br.lines().toArray();
            for(int i=0;i<lines.length;i++){
                String[] row=lines[i].toString().split(" ");
                tab.addRow(row);
            }
        } catch (IOException ex) {
            Logger.getLogger(ClientInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    public void dt(){

    Date d  =new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
    String dd = sdf.format(d);
    Date_txt.setText(dd);


}
   
 Timer t ;
 SimpleDateFormat st ;
    
public void times(){

        t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
        Date dt  =new Date();
        st = new SimpleDateFormat("hh:mm:ss:a");
        String tt = st.format(dt);
        Time_txt.setText(tt);
        
        }
    });
  
    t.start();
    
    

}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerInfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddOrder = new javax.swing.JButton();
        CustDashboard = new javax.swing.JButton();
        Quant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ProName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PriceProd = new javax.swing.JTextField();
        TotalOrd = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        OrderId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Time_txt = new javax.swing.JLabel();
        Date_txt = new javax.swing.JLabel();
        Check_Email = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        area_txt = new javax.swing.JTextArea();
        generateinvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerId", "Name", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerInfoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerInfoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerInfo);

        ProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Name", "Quantity", "Description", "Exp/Date", "Category", "Price", "Offer", "Start/End"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ProductList);

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "Name", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(OrderTable);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("CustomerInfo");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("ProductList");

        AddOrder.setBackground(new java.awt.Color(0, 51, 255));
        AddOrder.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        AddOrder.setForeground(new java.awt.Color(255, 255, 255));
        AddOrder.setText("AddOrder");
        AddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrderActionPerformed(evt);
            }
        });

        CustDashboard.setBackground(new java.awt.Color(0, 51, 255));
        CustDashboard.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CustDashboard.setForeground(new java.awt.Color(255, 255, 255));
        CustDashboard.setText("Home");
        CustDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustDashboardActionPerformed(evt);
            }
        });

        Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Quantity");

        ProName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("OrderId");

        PriceProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceProdActionPerformed(evt);
            }
        });

        TotalOrd.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        TotalOrd.setForeground(new java.awt.Color(0, 51, 255));
        TotalOrd.setText("Total");

        Print.setBackground(new java.awt.Color(0, 51, 255));
        Print.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText(" Print Invoice");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Name");

        OrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderIdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("=");

        Time_txt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Time_txt.setForeground(new java.awt.Color(0, 51, 255));
        Time_txt.setText("Time:");

        Date_txt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Date_txt.setForeground(new java.awt.Color(0, 51, 255));
        Date_txt.setText("Date:");

        Check_Email.setBackground(new java.awt.Color(0, 51, 255));
        Check_Email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Check_Email.setForeground(new java.awt.Color(255, 255, 255));
        Check_Email.setText("Check_Email");
        Check_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_EmailActionPerformed(evt);
            }
        });

        area_txt.setColumns(20);
        area_txt.setRows(5);
        jScrollPane4.setViewportView(area_txt);

        generateinvoice.setBackground(new java.awt.Color(0, 51, 255));
        generateinvoice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        generateinvoice.setForeground(new java.awt.Color(255, 255, 255));
        generateinvoice.setText("Generate");
        generateinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateinvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AddOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Check_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateinvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_txt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(PriceProd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(Time_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalOrd)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(generateinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Check_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Time_txt)
                            .addComponent(Date_txt))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(PriceProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalOrd)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(13, 13, 13))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int i=1, uprice,tot=0,total;

    private void AddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrderActionPerformed
            uprice=Integer.valueOf(PriceProd.getText());
            tot=uprice*Integer.valueOf(Quant.getText());
            Vector v=new Vector();
            v.add(OrderId.getText());
            v.add(ProName.getText());
            v.add(Quant.getText());
            v.add(PriceProd.getText());
            v.add(tot);
            DefaultTableModel dt=(DefaultTableModel)OrderTable.getModel();
            dt.addRow(v); 
            JOptionPane.showMessageDialog(this,"Added Sucessfully!");
            total=total+tot;
            TotalOrd.setText("$"+total);
            i++;
            
            
            //this is for placed orders by user
            String filepathorder="D:\\Files Project\\PlacedOrders.txt";
            File fileorder=new File(filepathorder);
            
        try {
            FileWriter fw2=new FileWriter(fileorder);
            BufferedWriter bw2=new BufferedWriter(fw2);
            for(int i=0;i<OrderTable.getRowCount();i++){
                for(int j=0;j<OrderTable.getColumnCount();j++){
                    bw2.write(OrderTable.getValueAt(i,j).toString()+" ");
                }
                bw2.newLine();
            }
            bw2.close();
            fw2.close();
        } catch (IOException ex) {
            Logger.getLogger(OrderDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            //for store into file
            String filepath="D:\\Files Project\\Profit.txt";
            File file=new File(filepath);
           try {
            FileWriter fw=new FileWriter(file);
            BufferedWriter bw=new BufferedWriter(fw);
            fw.write(String.valueOf(total));
            bw.close();
            fw.close();
           } catch (IOException ex) {
            Logger.getLogger(OrderDashboard.class.getName()).log(Level.SEVERE, null, ex);
          }
           
            
    }//GEN-LAST:event_AddOrderActionPerformed

    private void CustDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustDashboardActionPerformed
        this.setVisible(false);
        new ClientDashboard().setVisible(true);
    }//GEN-LAST:event_CustDashboardActionPerformed

    private void QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantActionPerformed

    private void ProNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProNameActionPerformed

    private void PriceProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceProdActionPerformed

    private void CustomerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerInfoMouseClicked

    }//GEN-LAST:event_CustomerInfoMouseClicked

    private void CustomerInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerInfoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerInfoMousePressed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        //for print the invoice
        try {
            area_txt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(OrderDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void OrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderIdActionPerformed

    private void Check_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_EmailActionPerformed
        //this is notification for placing order
        String message = "The order has been successfully requested";
        String header = "You Got A new Email";
        JFrame frame = new JFrame();
        frame.setSize(300,125);
        frame.setUndecorated(true);
        frame.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = 0;
        constraints.gridy = 0;
        constraints.weightx = 1.0f;
        constraints.weighty = 1.0f;
        constraints.insets = new Insets(5, 5, 5, 5);
        constraints.fill = GridBagConstraints.BOTH;
        JLabel headingLabel = new JLabel(header);
        headingLabel.setOpaque(false);
        frame.add(headingLabel, constraints);
        constraints.gridx++;
        constraints.weightx = 0f;
        constraints.weighty = 0f;
        constraints.fill = GridBagConstraints.NONE;
        constraints.anchor = GridBagConstraints.NORTH;
        JButton cloesButton = new JButton("X");
        cloesButton.setMargin(new Insets(1, 4, 1, 4));
        cloesButton.setFocusable(false);
        frame.add(cloesButton, constraints);
        constraints.gridx = 0;
        constraints.gridy++;
        constraints.weightx = 1.0f;
        constraints.weighty = 1.0f;
        constraints.insets = new Insets(5, 5, 5, 5);
        constraints.fill = GridBagConstraints.BOTH;
        JLabel messageLabel = new JLabel("<HtMl>"+message);
        frame.add(messageLabel, constraints);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize();// size of the screen
        Insets toolHeight = Toolkit.getDefaultToolkit().getScreenInsets(frame.getGraphicsConfiguration());// height of the task bar
        frame.setLocation(scrSize.width - frame.getWidth(), scrSize.height - toolHeight.bottom - frame.getHeight());
        new Thread(){
        @Override
        public void run() {
           try {
                  Thread.sleep(2000); // time after which pop up will be disappeared.
                  frame.dispose();
           } catch (InterruptedException e) {
                  e.printStackTrace();
           }
      };
}.start();
        
    }//GEN-LAST:event_Check_EmailActionPerformed
    int k=0,j=0;
    private void generateinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateinvoiceActionPerformed
        // this is for generate inovice to the text area to customer
        area_txt.setText("------------------------------------------------------------------\n");
        area_txt.setText(area_txt.getText()+"                         Food Land System\n");
        area_txt.setText(area_txt.getText()+"------------------------------------------------------------------\n");
        Date obj=new Date();
        String date =obj.toString();
        area_txt.setText(area_txt.getText()+"Customer Id is :"+CustomerInfo.getValueAt(CustomerInfo.getSelectedRow(),0)+""+"\n");
        area_txt.setText(area_txt.getText()+"Customer Name is :"+CustomerInfo.getValueAt(CustomerInfo.getSelectedRow(),1)+"\n");
        area_txt.setText(area_txt.getText()+"Customer Phone is :"+CustomerInfo.getValueAt(CustomerInfo.getSelectedRow(),2)+"\n");
        area_txt.setText(area_txt.getText()+"Customer Email is :"+CustomerInfo.getValueAt(CustomerInfo.getSelectedRow(),3)+"\n");
        area_txt.setText(area_txt.getText()+"\n"+date+"\n\n");
        area_txt.setText(area_txt.getText()+"Order id is :"+OrderId.getText()+"\n");
        area_txt.setText(area_txt.getText()+"Product name is :"+ProName.getText()+"\n");
        area_txt.setText(area_txt.getText()+"Quantity is :"+Quant.getText()+"\n");
        area_txt.setText(area_txt.getText()+"Price is: "+PriceProd.getText()+"\n");
        area_txt.setText(area_txt.getText()+"Total price is: "+total+"\n");
        
    }//GEN-LAST:event_generateinvoiceActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDashboard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrder;
    private javax.swing.JButton Check_Email;
    private javax.swing.JButton CustDashboard;
    private javax.swing.JTable CustomerInfo;
    private javax.swing.JLabel Date_txt;
    private javax.swing.JTextField OrderId;
    private javax.swing.JTable OrderTable;
    private javax.swing.JTextField PriceProd;
    private javax.swing.JButton Print;
    private javax.swing.JTextField ProName;
    private javax.swing.JTable ProductList;
    private javax.swing.JTextField Quant;
    private javax.swing.JLabel Time_txt;
    private javax.swing.JLabel TotalOrd;
    private javax.swing.JTextArea area_txt;
    private javax.swing.JButton generateinvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    public int getprofit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
